[versions]
hazelcast-spring = "5.5.0"
hazelcast-hibernate53 = "5.2.0"
jacoco = "0.8.13"
checkstyle = "10.23.1"
# jhipster-needle-gradle-dependency-catalog-version - JHipster will add additional versions for convention plugins heref

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.11.0" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version = "2024.0.1" }
springdoc-openapi-starter-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version = "2.8.8" }
hazelcast-spring = { module = "com.hazelcast:hazelcast-spring", version = "5.5.0" }
hazelcast-hibernate53 = { module = "com.hazelcast:hazelcast-hibernate53", version = "5.2.0" }
# jhipster-needle-gradle-dependency-catalog-libraries - JHipster will add additional libraries versions

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.4.5" }
# jhipster-needle-gradle-dependency-catalog-plugins - JHipster will add additional plugins versions
